//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBSQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        public long CourseId { get; set; }
        public string Title { get; set; }
        public string Credit { get; set; }
    }
}
