//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBSQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enrollment
    {
        public long EnrollmentId { get; set; }
        public Nullable<long> CourseId { get; set; }
        public Nullable<long> StudentId { get; set; }
        public Nullable<int> Grade { get; set; }
    }
}
